### ISSUE TITLE
note type change no longer applied in 2.1.24

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-keep-model-in-add-cards#2]
I tested with Anki 2.1.24 (8dfd362f) and only the add-on [Keep model of add cards](https://ankiweb.net/shared/info/424778276) installed. 

Now this problem occurs: In the Add window after selecting another note type in the "Choose Note Type" dialog the the new note type is not set/loaded: E.g. you see still the fields of the old note type in the editor and after adding I check the note type and see that it's still the old one.

The cause of the problem should be this commit: https://github.com/ankitects/anki/commit/0b633dbf402c369b15c2ff5c3d710993729df883  

If I re-add the line that this commit removed (`self.editor.setNote(note)`) into the Anki source code the add-on works.

I tried to solve this on my own for some time. But so far I've failed to add a fix to this add-on. I hope you can help because this add-on is essential for other add-ons I have.

**Comment by Arthur-Milchior** [comment]
Thank you for letting me know I'm breaking my own add-on. :p
I'll take a look at it

**Comment by aPaci95** [comment]
I have the same error

**Comment by Arthur-Milchior** [comment]
There was a mistake of mine in a recent PR in Anki and I sent a correction https://github.com/ankitects/anki/pull/584
Hopefully, it should get repaired by itself with update of anki.

**Comment by ijgnd** [comment]
Thank you Arthur for your quick work on this. You're indispensable here!

But it doesn't seem to work for me. I did this:

- I ran `git clone https://github.com/Arthur-Milchior/anki/`
- I changed into the cloned repo of yours.
- I ran `git checkout onModelchangeUsed`
- I started with `./run`
- I installed the add-ons [Opening the same window multiple time](https://ankiweb.net/shared/info/354407385) and [Keep model of add cards](https://ankiweb.net/shared/info/424778276) and restarted anki.
- Then I changed the note type. But the fields of the new note type are not loaded. Only after e.g. opening the fields or Cards dialog.

I made this screencast: At first I show the add-ons installed, then which version I use (notice the git commit id), then I change the note type, then I paste the debug info in the video: 

![](https://raw.githubusercontent.com/ijgnd/anki__help/master/screenshots/arthur_not_working.gif)

**Comment by Arthur-Milchior** [comment]
Please update

**Comment by ijgnd** [comment]
fixed. Thanks.

**Comment by hugomarins** [comment]
Arthur, I'm still having problems, even after you updated the add-on. (But I'm using Anki 2.1.24 yet, as the beta was having problems with some of my add-ons). Do I have to update to Anki beta or not?

For now, when I close one of the additional "Add" windows, it affects the other.

**Comment by Arthur-Milchior** [comment]
@hugomarins  The exact same error as described in the first comment ?
You updated your add-on recently ?
«But I'm using Anki 2.1.24 yet» did you forget a negation ? 
Current version is .26 fyi. 

I'm trying to keep my add-ons working, but I don't want to debug for older version.

**Comment by hugomarins** [comment]
Sorry, Arthur, I didn't realize that there was a newer stable version.

But now I installed Anki 2.1.26 and tested again. The problem is still there. I'll explain you what is happening, as it is not exactly the same problem of the first post.

Now, when I open an Add window, and then open another Add window, if I change the note type of the second Add window the first one will not be affected, **as long as I don't close the second Add window**. But if a close the second Add window when it is with a selected note type different of that of the first Add window, the first Add window will be affected, and the selected note type will suddenly change to that one that was selected in the second Add window by the time it was closed.

I hope you understand what I am trying to say.

That is to say that the changes you recently made solved a great part of the problem. But the first Add window is still being changed if the second Add window is closed. But now the fields that appear in this case (in the altered first Add window) correspond to the note type selected (that has been altered to that same of the second Add window).

If you need more info I'm here to help.

Thanks for all your efforts and for kindly sharing these amazing add-ons of yours!
